apiVersion: v1
kind: ConfigMap
metadata:
  name: csv-to-app-topology
  namespace: turbointegrations
  labels:
    environment: prod
    team: integration
    app: csv-to-app-topology
    version: 1.0.0
data:
  config.json: |
    {
      "INPUT_CSV_NAME": "test_csv.csv",
      "CSV_LOCATION": "FTP",
      "ENTITY_FIELD_MAP": {
        "app_name": "",
        "entity_name": "",
        "entity_ip": ""
      },
      "APP_PREFIX": "ATM-",
      "LOG_DIR": "",
      "LOG_FILE": "",
      "LOG_LEVEL": "DEBUG",
      "MATCH_IP": false
    }
